Chore/add revoke description to docs
uc-cdis/requestor pull request #63
Opened 2024-04-12 21:06 UTC by george42-ctds

### New Features

### Breaking Changes

### Bug Fixes

### Improvements

* Add a description of how to remove access in the `authorization` document.

### Dependency updates

* authlib to 1.3.0
* cryptography to 42.0.5
* idna to 3.7
* pydantic to 1.10.15

### Deployment changes

2024-04-12 21:23 UTC, smvgarcia approved these changes
Love it! thanks, George!

2024-04-12 22:20 UTC, paulineribeyre requested changes

2024-04-12 22:20 UTC, paulineribeyre commented on docs/authorization.md
> +The user's access will be revoked when the new request has been approved by an administrator.
```suggestion
Just like access requests, revocation requests must be approved before they take effect. The user's access will be revoked when the new request has been approved by an administrator.

**IMPORTANT NOTE:** Requestor can only revoke access that has been granted through Requestor.
What does this mean? Access granted through the [user.yaml file](https://github.com/uc-cdis/fence/blob/master/docs/user.yaml_guide.md) cannot be revoked by Requestor. Similarly, removing access through the user.yaml file will not revoke access granted by Requestor.
```

2024-04-15 14:59 UTC, paulineribeyre submitted a review, later dismissed
Thanks!

2024-04-15 16:41 UTC, george42-ctds commented on docs/authorization.md
> +The user's access will be revoked when the new request has been approved by an administrator.
Nice! Thank you for the clarifications!

2024-04-15 22:26 UTC, paulineribeyre approved these changes

2024-04-15 22:27 UTC, george42-ctds commented
The poetry.lock was reverted to master because the dependency upgrades were handled in the dependabot PRs.

2024-04-15 22:28 UTC, merged